### ISSUE TITLE
Interrupt Pin Issues

### ISSUE THREAD

**Issue by trifour2** [adafruit/Adafruit_CircuitPython_VCNL4040#12]
I was trying to implement the interrupt pin, but with little success. I tried a number of combinations of the code below, but I can never measure 3V on the interrupt pin of the board. Therefore I cannot see when the interrupt pin is getting pulled low (I'm always reading 0V at the interrupt pin). Could I get an example of how to implement the interrupt pin, because maybe I am misunderstanding how interrupt pin works in general?

import time
import board
import busio
import adafruit_vcnl4040

i2c = busio.I2C(board.SCL, board.SDA)
sensor = adafruit_vcnl4040.VCNL4040(i2c)

sensor.proximity_interrupt= sensor.PS_INT_CLOSE
sensor.proximity_integration_time= sensor.PS_2T
sensor.proximity_high_threshold = 5

**Comment by ladyada** [comment]
do you have a pullup on it?

**Comment by trifour2** [comment]
I did not. Thank you for your help.
